### ISSUE TITLE
解决低横纵比与窄屏幕时拖动条过短

### ISSUE THREAD

**Issue by OrikesC** [WuMianzhi/my-unique-gender#15]
**Describe the solution you'd like**
用 media rule 在屏幕窄时设 display: block 换行文字与拖动条

**Comment by OrikesC** [comment]
如果加上图片的话再换行可能会使排版过长...比起这个拖动条的长度应该可以接受

**Comment by WuMianzhi** [comment]
现在对于小屏的适配较好，但是对于大屏的适配需要进一步优化
