### ISSUE TITLE
移动端设配不完善·

### ISSUE THREAD

**Issue by WuMianzhi** [WuMianzhi/my-unique-gender#5]
目前，部分机型出现
1. 字体缺失
2. 排版混乱，部分字地方没有对齐
3. 字体忽大忽小

**Comment by OrikesC** [comment]
用firefox的responsive design mode测试是宽380px以下时不能完美居中，内置的一些机型（如Galaxy S10、iPhone 11 Pro）宽不足380px，但都在360px以上

**Comment by OrikesC** [comment]
字体的话用css指定下字体和相对大小应该就可以？

**Comment by WuMianzhi** [comment]
这里我现在用的是tailwind css标签的默认大小，需要进一步适配

**Comment by OrikesC** [comment]
在窄屏幕拖动条会变得过短，可能需要文字和拖动条之间换行

**Comment by WuMianzhi** [comment]
> #15

已经适配了SE晓平，但是再大一点的屏幕感觉字体有点小了
